---
# global vars for librenms_server deployment

update_channel: release
# nginx or apache
webserver: nginx
time_zone: America/Chicago
php_version: 7.4 # for debian installs
# mariadb bind address
service_account: librenms
core_server_fqdn: "{{ ansible_facts.default_ipv4.address }}"
# dir to add to service account path for lnms binary
new_path: /usr/local/bin
snmp_string: public
snmp_port: 161
snmp_v3_auth:
  authlevel: authPriv
  authname: snmp_user
  authpass: pass
  authalgo: SHA
  cryptopass: pass
  cryptoalgo: AES
syslog_port: 514
app_key: base64:12345=
auto_scan_subnets: # subnets included in automatic discovery
  - 10.1.10.0/24
  - 10.1.40.0/24

exclude_scan_subnets: # subnets excluded from automatic discovery
  - 10.1.10.1/32
  - 10.1.40.1/32

# mysql vars
# mysql_root_password_update: false
# mysql_enabled_on_startup: true
# mysql_root_password: super-secure-password
# mysql_databases:
#   - name: librenms
#     encoding: utf8
#     collation: utf8_unicode_ci
# mysql_users:
#   - name: librenms
#     host: "%"
#     password: librenms
#     priv: "librenms.*:ALL"

mariadb_bind_address: "0.0.0.0"

mariadb_databases:
  - name: librenms
    encoding: utf8
    collation: utf8_unicode_ci
mariadb_users:
  - name: librenms
    host: "%"
    password: librenms
    priv: "librenms.*:ALL"

database_settings:
  - old_line: "^#DB_HOST="
    new_line: "DB_HOST={{ core_server_fqdn }}"
  - old_line: "^#DB_DATABASE="
    new_line: "DB_DATABASE={{ mariadb_databases[0].name }}"
  - old_line: "^#DB_USERNAME="
    new_line: "DB_USERNAME={{ mariadb_users[0].name }}"
  - old_line: "^#DB_PASSWORD="
    new_line: "DB_PASSWORD={{ mariadb_users[0].password }}"

debian_rrdcached_settings:
  - old_line: "DAEMON"
    new_line: "DAEMON=/usr/bin/rrdcached"
  - old_line: "WRITE_TIMEOUT"
    new_line: "WRITE_TIMEOUT=1800"
  - old_line: "WRITE_JITTER"
    new_line: "WRITE_JITTER=1800"
  - old_line: "WRITE_THREADS"
    new_line: "WRITE_THREADS=4"
  - old_line: "BASE_PATH"
    new_line: "BASE_PATH=/opt/librenms/rrd"
  - old_line: "JOURNAL_PATH"
    new_line: "JOURNAL_PATH=/var/lib/rrdcached/journal/"
  - old_line: "PID_FILE"
    new_line: "PID_FILE=/var/run/rrdcached.pid"
  - old_line: "SOCKFILE"
    new_line: "SOCKFILE=/run/rrdcached.sock"
  - old_line: "SOCKGROUP"
    new_line: "SOCKGROUP={{ service_account }}"
  - old_line: "DAEMONGROUP"
    new_line: "DAEMON_GROUP={{ service_account }}"
  - old_line: "DAEMON_USER"
    new_line: "DAEMON_USER={{ service_account }}"
  - old_line: "BASE_OPTIONS"
    new_line: 'BASE_OPTIONS="-B -F -R"'
  - old_line: "NETWORK_OPTIONS"
    new_line: 'NETWORK_OPTIONS="-L"'
