---
collections:
  - name: ansible.posix
    source: https://galaxy.ansible.com
    version: 1.1.1
  - name: community.general
    source: https://galaxy.ansible.com
    version: 1.2.0
  - name: community.mysql
    source: https://galaxy.ansible.com
    version: 1.1.1

roles:
  - name: adfinis-sygroup.mariadb
    source: https://galaxy.ansible.com
