---
- name: Deploy LibreNMS Core Server
  hosts: all
  gather_facts: True
  become: True

  tasks:
    - import_role:
        name: geerlingguy.mysql

    - name: Import librenms_server role
      import_role:
        name: librenms_server
