---

- name: Deploy LibreNMS Core Server
  hosts: all
  gather_facts: true
  become: true

  tasks:
    - name: Install MariaDB Ubuntu/Debian
      apt:
        package:
          - mariadb-server
          - mariadb-client
        state: present
        update_cache: true
      when: ansible_os_family == 'Debian'

    # - import_role:
    #     name: geerlingguy.mysql

    - name: Import mariadb role
      import_role:
        name: adfinis-sygroup.mariadb

    - name: Import librenms_server role
      import_role:
        name: librenms_server
