---

- name: Deploy LibreNMS Core Server
  hosts: all
  gather_facts: true
  become: true

  tasks:
    - name: Import librenms_server role
      import_role:
        name: librenms_server
