---
- name: Deploy LibreNMS Core Server
  hosts: all
  gather_facts: False
  become: True

  tasks:
    - name: Configure rsyslog to accept syslogs
      lineinfile:
        path: /etc/rsyslog.conf
        insertafter: '^\#input\(type=\"imudp\" port=\"514\"\)$'
        line: |
          module(load="imudp")
          input(type="imudp" port="{{ syslog_port }}")
