---
- name: Deploy LibreNMS Core Server
  hosts: all
  gather_facts: False
  become: True

  tasks:
    - name: Enable lnms command completion - link
      file:
        src: /opt/librenms/lnms
        dest: /usr/local/bin/lnms
        state: link
