---
debian_prerequisites:
  - acl
  - curl
  - composer
  - fping
  - git
  - graphviz
  - imagemagick
  - mariadb-client
  - memcached
  #- mariadb-server
  - mtr-tiny
  - nmap
  - php-cli
  - php-curl
  - php-fpm
  - php-gd
  - php-json
  - php-memcached
  - php-mbstring
  - php-mysql
  - php-snmp
  - php-xml
  - php-zip
  - rrdcached={{ rrdcached_version }}
  - rrdtool
  - snmp
  - snmpd
  - whois
  - unzip
  - python3-pymysql
  - python3-dotenv
  - python3-redis
  - python3-setuptools
  - "{{ web_server }}"
