---
redhat_prerequisites:
  - bash-completion
  - cronie
  - fping
  - git
  - ImageMagick
  #- mariadb-client
  - memcached
  - mtr
  - net-snmp
  - net-snmp-utils
  - nmap
  - php-fpm
  - php-cli
  - php-common
  - php-curl
  - php-gd
  - php-json
  - php-mbstring
  - php-process
  - php-snmp
  - php-xml
  - php-zip
  - php-mysqlnd
  - policycoreutils-python-utils
  - python3
  - python3-PyMySQL
  - python3-memcached
  - python3-pip
  - rrdcached={{ rrdcached_version }}
  - rrdtool
  - unzip
