---

php_service: php{{ php_version }}-fpm

rrdcached_version: 1.7.2

debian_prerequisites:
  - acl
  - curl
  - composer
  - fping
  - git
  - graphviz
  - imagemagick
  - memcached
  - mtr-tiny
  - nmap
  - php-cli
  - php-curl
  - php-fpm
  - php-gd
  - php-json
  - php-memcached
  - php-mbstring
  - php-mysql
  - php-snmp
  - php-xml
  - php-zip
  - rrdcached
  - rrdtool
  - snmp
  - snmpd
  - whois
  - unzip
  - python3-pymysql
  - python3-dotenv
  - python3-redis
  - python3-setuptools
  - mariadb-server
