---
# tasks file for librenms_server

- name: Install proper webserver
  import_tasks: webserver.yml

- name: Install Mariadb
  package:
    name: mariadb-server
    state: present

- name: Setup Mariadb
  import_tasks: ./mariadb.yml

- name: Import vars for Debian-based OS
  include_vars:
    file: vars/debian.yml
  when:
    - ansible_lsb.id is defined
    - not ansible_lsb.id == 'Raspbian'
    - ansible_distribution == 'Debian'

- name: Install Prerequisites for Debian-based OS
  import_tasks: debian.yml
  when:
    - ansible_lsb.id is defined
    - not ansible_lsb.id == 'Raspbian'
    - ansible_distribution == 'Debian'

- name: Import vars for Ubuntu-based OS
  include_vars:
    file: vars/ubuntu.yml
  when:
    - ansible_lsb.id is defined
    - not ansible_lsb.id == 'Raspbian'
    - ansible_distribution == 'Ubuntu'

- name: Install Prerequisites for Ubuntu-based OS
  import_tasks: ubuntu.yml
  when:
    - ansible_lsb.id is defined
    - not ansible_lsb.id == 'Raspbian'
    - ansible_distribution == 'Ubuntu'

- name: Import vars for CentOS/RedHat-based OS
  include_vars:
    file: vars/redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Install Prerequisites for CentOS/RedHat-based OS
  import_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Alter Database Collation
  community.mysql.mysql_query:
    login_db: "{{ mariadb_databases[0].name }}"
    query: ALTER DATABASE librenms CHARACTER SET utf8 COLLATE utf8_unicode_ci;

- name: Get latest librenms release
  uri:
    url: https://api.github.com/repos/librenms/librenms/releases/latest
    return_content: true
  delegate_to: localhost
  register: json_response
  become: false
  run_once: true

- name: Check if Librenms repository exists
  stat:
    path: /opt/librenms/README.md
  register: stat_result

- name: Clone Librenms Repository
  git:
    repo: https://github.com/librenms/librenms.git
    dest: /opt/librenms
    clone: true
    # version: "{{ json_response.json.tag_name }}"
    force: true
    # when: not stat_result.stat.exists

- name: Add Librenms service account
  user:
    name: "{{ service_account }}"
    comment: librenms service account
    create_home: True
    home: /opt/librenms
    shell: /bin/bash
    state: present

- name: Add Nginx user to {{ service_account }} group
  user:
    name: nginx
    groups:
      - "{{ service_account }}"
    append: true
  when:
    - webserver == 'nginx'

- name: Add another bin dir to system-wide $PATH.
  copy:
    dest: /etc/profile.d/custom-path.sh
    content: "PATH=$PATH:{{ new_path }}"

- name: Chown librenms /opt/librenms
  file:
    path: /opt/librenms
    owner: "{{ service_account }}"
    group: "{{ service_account }}"
    mode: "771"
    recurse: true

- name: Add current user to {{ service_account }} group
  user:
    name: "{{ ansible_user }}"
    groups:
      - "{{ service_account }}"
    append: true

- name: Install PHP composer as librenms user
  become: true
  become_user: "{{ service_account }}"
  vars:
    ansible_command_timeout: 3600
  shell: ./scripts/composer_wrapper.php install --no-dev
  args:
    chdir: /opt/librenms

- name: Set server timezone
  community.general.timezone:
    name: "{{ time_zone }}"

# - name: Create Logins for MariaDB On Core Server
#   community.mysql.mysql_user:
#     name: librenms
#     host: "{{ poller_ip }}"
#     password: "{{ mysql_password }}"
#     priv: "librenms.*:ALL"
#     state: present
#     login_host: "{{ core_server_fqdn }}"
#     login_user: "{{ core_db_user }}"
#     login_password: "{{ core_db_password }}"

- name: Configure rsyslog to accept syslogs
  lineinfile:
    path: /etc/rsyslog.conf
    insertafter: '^\#input\(type=\"imudp\" port=\"514\"\)$'
    line: |
      module(load="imudp")
      input(type="imudp" port="{{ syslog_port }}")

- name: Configure rsyslog to forward syslogs to core server
  template:
    src: templates/30-librenms.j2
    dest: /etc/rsyslog.d/30-librenms.conf

- name: Restart rsyslog service
  service:
    name: rsyslog
    state: restarted

- name: Enable lnms command completion - link
  file:
    src: /opt/librenms/lnms
    dest: /usr/local/bin/lnms
    state: link

- name: Enable lnms command completion - copy file
  copy:
    remote_src: true
    src: /opt/librenms/misc/lnms-completion.bash
    dest: /etc/bash_completion.d/

- name: Configure SNMPD
  import_tasks: snmpd.yml

# - name: Configure SNMP default v2c string
#   lineinfile:
#     path: /opt/librenms/config.php.default
#     regex: '\$config\['snmp'\]\['community'\]'
#     line: ""$config['snmp']['community'] = array('{{ snmp_string }}');
#   when: snmp_string is defined

- name: Download SNMP Distro
  get_url:
    url: https://raw.githubusercontent.com/librenms/librenms-agent/master/snmp/distro
    dest: /usr/bin/distro

- name: Set permissions on snmp distro
  file:
    path: /usr/bin/distro
    mode: u+x,g+x,o+x

- name: Enable and restart snmpd
  service:
    name: snmpd
    state: restarted
    enabled: true

- name: Copy Cron Job
  copy:
    remote_src: True
    src: /opt/librenms/dist/librenms.cron
    dest: /etc/cron.d/librenms

- name: Copy LibreNMS Scheduler Service
  copy:
    remote_src: True
    src: /opt/librenms/dist/librenms-scheduler.service
    dest: /etc/systemd/system/

- name: Copy LibreNMS Scheduler Timer
  copy:
    remote_src: True
    src: /opt/librenms/dist/librenms-scheduler.timer
    dest: /etc/systemd/system/

- name: Force systemd to re-execute itself
  ansible.builtin.systemd:
    daemon_reexec: true

- name: Enable Scheduler Timer
  service:
    name: librenms-scheduler.timer
    state: restarted
    enabled: True

- name: Copy logrotate config
  copy:
    remote_src: true
    src: /opt/librenms/misc/librenms.logrotate
    dest: /etc/logrotate.d/librenms

- name: Enable SNMP Scans at 11pm Nightly
  lineinfile:
    path: /etc/cron.d/librenms
    insertbefore: EOF
    line: "0 23 * * * {{ service_account }} /opt/librenms/snmp-scan.py >> /opt/librenms/logs/snmp-scan.log"

- name: Update Database settings in /opt/librenms/.env
  lineinfile:
    path: /opt/librenms/.env
    regex: "{{ item.old_line }}"
    line: "{{ item.new_line }}"
  with_items: "{{ database_settings }}"
  no_log: true

- name: Update RRDCached Config Debian
  lineinfile:
    path: /etc/default/rrdcached
    regex: "{{ item.old_line }}"
    line: "{{ item.new_line }}"
  with_items: "{{ debian_rrdcached_settings }}"
  when: ansible_os_family == 'Debian'

# - name: Update RRDCached settings in config.php.default
#   lineinfile:
#     path: /opt/librenms/config.php.default
#     insertbefore: EOF
#     line: "{{ item }}"
#   with_items:
#     - $config['rrdcached'] = "{{ core_server_fqdn }}:42217";
#     - $config['rrdtool_version'] = '{{ rrdcached_version }}';
#     - $config['enable_syslog'] = 1;
#     - $config['update_channel'] = "{{ update_channel }}";

- name: Remove default config file
  file:
    path: /opt/librenms/config.php.default
    state: absent

- name: Template config.php.default
  template:
    src: templates/config_php.j2
    dest: /opt/librenms/config.php.default
    force: true
    owner: "{{ service_account }}"
    group: "{{ service_account }}"
    mode: "0771"

# - name: Stash git changes
#   command: "/opt/librenms/scripts/github-remove -s"

- name: Chown/chmod librenms /opt/librenms
  file:
    path: /opt/librenms
    owner: "{{ service_account }}"
    group: "{{ service_account }}"
    mode: "0771"
    recurse: true

- name: Grant librenms ACL permissions to rrd/logs/bootstrap
  ansible.posix.acl:
    path: "{{ item }}"
    entity: "{{ service_account }}"
    etype: group
    permissions: rwx
    default: true
    recursive: true
    state: present
  with_items:
    - /opt/librenms/rrd/
    - /opt/librenms/logs/
    - /opt/librenms/bootstrap/cache/
    - /opt/librenms/storage/

- name: Set 775 on RRD folder
  file:
    path: /opt/librenms/rrd
    mode: "0775"

- name: Set 775 on HTML Folder Debian
  file:
    path: /opt/librenms/html
    mode: "0775"
    recurse: true
  when: ansible_os_family == 'Debian'

- name: Create librenms Nginx server config file
  template:
    src: templates/nginx_libre_template.j2
    dest: /etc/nginx/conf.d/librenms.conf

- name: Start Nginx and PHP services
  service:
    name: "{{ item }}"
    state: restarted
    enabled: true
  with_items:
    - nginx
    - "{{ php_service }}"
    - rrdcached

- name: reset the connection
  meta: reset_connection

- name: Wait 10 Seconds
  wait_for_connection:
    delay: 10

- name: Reboot if debian
  reboot:
  register: reboot
  when: ansible_os_family == 'Debian'

- name: Wait for reboot
  wait_for:
    timeout: 120
  when: reboot.changed

- name: Validate installation
  shell: /opt/librenms/validate.php
  register: validate_results
  become: false

- name: Print results
  debug:
    var: validate_results.stdout_lines
