---

- name: Enable universe repository x86
  apt_repository:
    repo: deb http://archive.ubuntu.com/ubuntu {{ ansible_facts.distribution_release }} universe
    state: present
    update_cache: true
  when:
    - not ansible_architecture is search("arm")
    - not ansible_architecture == 'aarch64'
    - ansible_distribution == 'Ubuntu'

- name: Install Ubuntu Prerequisite Packages
  apt:
    package: "{{ debian_prerequisites }}"
    state: present
    update_cache: true

- name: Set Timezone PHP Debian
  lineinfile:
    path: "{{ item }}"
    regexp: "date.timezone"
    line: "date.timezone = {{ time_zone }}"
  with_items:
    - /etc/php/{{ php_version }}/fpm/php.ini
    - /etc/php/{{ php_version }}/cli/php.ini

- name: Configure mariadb server conf
  lineinfile:
    path: /etc/mysql/conf.d/server.cnf
    insertafter: '^\[mysqld\]'
    line: |
      innodb_file_per_table=1
      lower_case_table_names=0

- name: Restart mariadb service
  service:
    name: mariadb
    state: restarted

- name: Copy www.conf to librenms.conf
  copy:
    remote_src: true
    src: /etc/php/{{ php_version }}/fpm/pool.d/www.conf
    dest: /etc/php/{{ php_version }}/fpm/pool.d/librenms.conf

- name: Change PHP-FPM www to librenms
  lineinfile:
    path: /etc/php/{{ php_version }}/fpm/pool.d/librenms.conf
    regex: '\[www\]'
    line: "[librenms]"

- name: Update PHP-FPM user to librenms
  lineinfile:
    path: /etc/php/{{ php_version }}/fpm/pool.d/librenms.conf
    regex: '^user\ ='
    line: "user = librenms"

- name: Update PHP-FPM group to librenms
  lineinfile:
    path: /etc/php/{{ php_version }}/fpm/pool.d/librenms.conf
    regex: '^group\ ='
    line: "group = librenms"

- name: Update listen to a unique name
  lineinfile:
    path: /etc/php/{{ php_version }}/fpm/pool.d/librenms.conf
    regex: '^listen\ ='
    line: "listen = /run/php-fpm-librenms.sock"

- name: Remove default nginx site file
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Update Nginx librenms site conf file
  template:
    src: templates/nginx_libre_template.j2
    dest: /etc/nginx/sites-available/librenms.conf
