---
# load proper webserver

- name: Remove Nginx when wanted Apache
  package:
    name: nginx
    state: absent
  when: webserver == 'apache'

- name: Remove Apache from Debian based-server when wanted Nginx
  package:
    name: apache2
    state: absent
  when:
    - webserver == 'nginx'
    - ansible_os_family == 'Debian'

- name: Remove Apache from RedHat based-server when wanted Nginx
  package:
    name: httpd
    state: absent
  when:
    - webserver == 'nginx'
    - ansible_os_family == 'RedHat'

- name: Install Nginx Web Server
  package:
    name: nginx
    state: present
  when:
    - webserver == 'nginx'

- name: Install Apache Web Server on Debian-based OS
  package:
    name: apache2
    state: present
  when:
    - webserver == 'apache'
    - ansible_os_family == 'Debian'

- name: Install Apache Web Server on CentOS/RedHat-based OS
  package:
    name: httpd
    state: present
  when:
    - webserver == 'apache'
    - ansible_os_family == 'RedHat'
